apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{ .Release.Name }}-homehello'
  labels:
    katenary.io/component: homehello
    katenary.io/project: '{{ .Chart.Name }}'
    katenary.io/release: '{{ .Release.Name }}'
  annotations:
    katenary.io/docker-compose-sha1: 206531491f1b9d82a0bfbd36182be21f1b2d6beb
    katenary.io/version: 2.0.0-beta2
spec:
  replicas: 1
  selector:
    matchLabels:
      katenary.io/component: homehello
      katenary.io/release: '{{ .Release.Name }}'
  template:
    metadata:
      labels:
        katenary.io/component: homehello
        katenary.io/release: '{{ .Release.Name }}'
    spec:
      containers:
        - name: homehello
          image: '{{ .Values.homehello.repository.image }}{{ if ne .Values.homehello.repository.tag "" }}:{{ .Values.homehello.repository.tag }}{{ end }}'
          ports:
            - name: homehello
              containerPort: 3000

